input_dir: /exp/sbnd/data/users/liangliu/cc-inclusive/lists
output_dir: /exp/sbnd/data/users/liangliu/cc-inclusive/dfs

jobs:
  - name: mcbnb_vtx3000
    enabled: true
    description: 3000-file truth-only run (hdr+mcnu) for neutrino vertex x/y/z validation plots
    base_config: analysis_village.numuincl.configs.base
    dfs:
      - makedf.makedf.make_hdrdf
      - makedf.makedf.make_mcnudf
    names: [hdr, mcnu]
    input_list: mcbnb_cv_vtx3000.list
    output: mcbnb_cv_vtx3000
    settings:
      INCLUDE_WEIGHTS: false
      SLIM: false
      UPDATE_RECOMB: true
      VERBOSE: true
      ADD_STAT_UNC: false
    args:
      ngrid: 0
      ncpu: -1
      nfile: -1
